import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
var link = document.createElement('link');
link.setAttribute('rel','stylesheet');
link.setAttribute('type','text/css');
link.setAttribute('href','https://fonts.googleapis.com/css?family=Quattrocento+Sans');
if (typeof window === 'object') {
  document.head.appenChild(link);
}


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Jessica&apos;s website!
        </h1>

        <p className={styles.description}>
          My new site is currently under construction so please bear with me.
        </p>
 


        <div className={styles.grid}>
          <a href="https://www.instagram.com/jessc.miller" className={styles.card}>
            <h2>Instagram &rarr;</h2>
          </a>

          <a href="https://www.twitter.com/jessicacmiller_" className={styles.card}>
            <h2>Twitter &rarr;</h2>
          </a>

          <a href="http://www.materialityexposed.com" className={styles.card}>
            <h2>Materiality Exposed exhibition &rarr;</h2>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
