import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Jessica&apos;s website!
        </h1>

        <p className={styles.description}>
          My new site is currently under construction so please bear with me. In the meantime check out my social media
        </p>
 
document.addEventListener('DOMContentLoaded',function(){
 
//Initialize Fixed floating btn
const shareButtons = document.querySelector('.fixed-action-btn');
M.FloatingActionButton.init(shareButtons,{
	hoverEnabled:false
});
 
 
//Getting page information
let current_url = window.location.href;
let currentPage_title = document.title;
 
//Get icon ids
let facebook = document.getElementById('fb');
let twitter = document.getElementById('tw');
let whatsapp = document.getElementById('wts');
let linkedIn = document.getElementById('lnk');
let googlePlus = document.getElementById('gp');
 
//Facebook
facebook.addEventListener('click',function(){
	let fb_shareUrl = "https://www.facebook.com/sharer/sharer.php?u="+current_url;
	let window_size = "width=565,height=569";
	window.open(fb_shareUrl,"","menubar=no,resizeable=yes,scrollbars=yes,"+window_size);
	return false;
});
 
 
//Twitter
twitter.addEventListener('click',function(){
	let tw_shareUrl = "https://twitter.com/intent/tweet?text="+currentPage_title+"&url="+current_url;
	let window_size = "width=565,height=569";
	window.open(tw_shareUrl,"","menubar=no,resizeable=yes,scrollbars=yes,"+window_size);
	return false;
});
 
 
//Whatapp
whatsapp.addEventListener('click',function(){
	let wts_shareUrl = "whatsapp://send?text="+current_url;
	let window_size = "width=565,height=569";
	window.open(wts_shareUrl,"","menubar=no,resizeable=yes,scrollbars=yes,"+window_size);
	return false;
});
 
 
//LinkedIn
linkedIn.addEventListener('click',function(){
	let lnk_shareUrl = "https://www.linkedin.com/cws/share?url="+current_url;
	let window_size = "width=565,height=569";
	window.open(lnk_shareUrl,"","menubar=no,resizeable=yes,scrollbars=yes,"+window_size);
	return false;
});
 
 
//Google Plus
googlePlus.addEventListener('click',function(){
	let gp_shareUrl = "https://plus.google.com/share?url="+current_url;
	let window_size = "width=565,height=569";
	window.open(gp_shareUrl,"","menubar=no,resizeable=yes,scrollbars=yes,"+window_size);
	return false;
});
 
 
});
	

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
